# Generated by Django 3.2.7 on 2021-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='B_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Capture name'),
        ),
        migrations.AlterField(
            model_name='business',
            name='Owner_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Info'),
        ),
    ]
